# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surl', '0003_remove_link_wdkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='wdkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surl.relate'),
        ),
    ]
