# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surl', '0004_link_wdkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='wdkey',
        ),
    ]
