# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surl', '0005_remove_link_wdkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='word_ind',
            field=models.IntegerField(null=True),
        ),
    ]
