# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surl', '0008_auto_20160412_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='relate',
            name='usedflag',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
